### ISSUE TITLE
Documentation suggestion for Requests and Responses

### ISSUE THREAD

**Issue by dashtodartlang** [angel-dart/roadmap#14]
Suggestion for documentation change at:
https://github.com/angel-dart/angel/wiki/Requests-&-Responses

**Please read carefully.  A lot of this may not be accurate!**

When a browser sends a message to the server, that message is called a request.  After the request is received, the server needs to do something.  The method or series of methods that determine the next step is called a handler.  Frequently, the handler, handles the request by sending back a response the the browser.  

Angel works by using 2 objects, RequestContext and ResponseContext.  These correspond to requests that the browser sends, and the response that Angel returns to the browser, respectively.  By instantiating these different types in Angel, it gives us a lot of flexibility in how we handle the data.

RequestContext and ResponseContext are 2 optional parameters when using app.get  -  is this correct?

Example:  app.get('/', (RequestContext request, ResponseContext response) async => "Hello, World!");
RequestContext - contains vital information from the client. 
ResponseContext - sends information to the client.  

The use of RequestContext is as follows:
****  I don’t think this is right at all.
app.get(“/”, (RequestContext request, ResponseContext response) {
    request.body  // does something.  Unfortunately, I don’t understand these methods at all.  If you just give me a few examples of what the methods do, maybe I can figure the rest out.
    request.files  // Please explain what it does
    request.****  // the rest of the RequestContext methods
    Either link to documentation, or even explain all RequestContext methods here.
});

The use of RequestResponse is as follows:
app.get(“/”, (RequestContext request, ResponseContext response) {
    response.body  // does something.  Unfortunately, I don’t understand these methods at all either.
    response.buffer  // please give example of result
    response.****  // what does this do
});

Return values, Other parameters, Queries, Files, and Bodies:
You can have a separate section here if you want, or just put it all up above.  Most importantly, please provide an example of each method.  Sometimes you need more than 1 example, to truly show the full potential of the methods.

**Comment by thosakwe** [comment]
Going to mark this as closed. Let me know if you need further explanation!
